ShowSprites:            true
ScriptEditor:           ~
Translucency:           50
Language:               ~
CreateBackups:          true
MapSortOrder:           0
HexPrefix:              0x
ShowRawMapHeader:       false
ShowRawLayoutHeader:    false
ShowGrid:               false
MapAccuracyLevel:       4
LastPath:               ~
RecentFiles:            ~
